version: "2.2"
services:
    web:
        build: 
            context: ../../..
            dockerfile: docker/instances/workcopy/dockerfiles/web.Dockerfile
        ports:
            - "$HTTP_PORT_BACK:80"
        tty: 
            true
        depends_on:
            - app      
        networks:
            net:
        volumes:
            - ../../../engine:/var/www/html
#            - ../../../docs/swagger:/var/www/html/public/swagger
#            - /tmp/mpsock:/tmp/mpsock
    app:
        extends:
            file: include/app.common.yml
            service: app
        command:
            /app.sh

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: $NETWORK
